project_id = "xksuhebsnodtyvwhlzlm"

[functions.process-spreadsheet]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.update-password]
verify_jwt = true

[functions.reprocess-refunds]
verify_jwt = false

[functions.ingest-revenue]
verify_jwt = false

[functions.redirect-short-link]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.ingest-stock]
verify_jwt = false

[functions.delete-user]
verify_jwt = true
